import { Project } from "@/types/portfolio";

export const PROJECTS: Project[] = [
  {
    id: "smartfleet-v2",
    slug: "smartfleet-v2",
    title: "SMARTFLEET V2",
    category: { es: "PROYECTO PERSONAL", en: "PERSONAL PROJECT" },
    projectCategory: "personal",
    status: "functional",
    subtitle: {
      es: "Centraliza telemetría simulada de flotas para registrar señales operativas, consultar historiales, generar alertas mediante reglas y visualizar resultados en mapas y paneles. Integra diferentes modelos de almacenamiento para analizar vehículos, conductores e incidentes.",
      en: "Centralizes simulated fleet telemetry to record operational signals, query historical data, generate rule-based alerts, and visualize results through maps and dashboards. It integrates different storage models to analyze vehicles, drivers, and incidents.",
    },
    tagline: {
      es: "Centraliza telemetría simulada de flotas para registrar señales operativas, consultar historiales, generar alertas mediante reglas y visualizar resultados en mapas y paneles. Integra diferentes modelos de almacenamiento para analizar vehículos, conductores e incidentes.",
      en: "Centralizes simulated fleet telemetry to record operational signals, query historical data, generate rule-based alerts, and visualize results through maps and dashboards. It integrates different storage models to analyze vehicles, drivers, and incidents.",
    },
    description: {
      es: "Centraliza telemetría simulada de flotas para registrar señales operativas, consultar historiales, generar alertas mediante reglas y visualizar resultados en mapas y paneles. Integra diferentes modelos de almacenamiento para analizar vehículos, conductores e incidentes.",
      en: "Centralizes simulated fleet telemetry to record operational signals, query historical data, generate rule-based alerts, and visualize results through maps and dashboards. It integrates different storage models to analyze vehicles, drivers, and incidents.",
    },
    details: {
      es: "SmartFleet V2 organiza datos simulados de telemetría para visualizar el estado de vehículos y analizar eventos operativos. Recibe ubicación, velocidad, combustible, RPM y temperatura; almacena las lecturas en Cassandra, consulta vehículos y umbrales en PostgreSQL y registra alertas e incidentes en MongoDB. El backend expone endpoints de ingesta, análisis, consultas y actualizaciones mediante Server-Sent Events. La interfaz React presenta mapas, gráficos e historiales que conectan almacenamiento, reglas de negocio y visualización de datos dentro de un escenario logístico simulado.",
      en: "SmartFleet V2 organizes simulated telemetry data to visualize vehicle status and analyze operational events. It receives location, speed, fuel, RPM, and temperature readings; stores telemetry in Cassandra, queries vehicles and thresholds in PostgreSQL, and records alerts and incidents in MongoDB. The backend exposes ingestion, analysis, query, and Server-Sent Events endpoints. The React interface provides maps, charts, and historical views connecting storage, business rules, and data visualization within a simulated logistics scenario.",
    },
    contribution: {
      es: "Diseñé y estructuré el flujo de telemetría simulada desde la ingesta hasta la consulta y visualización. Integré persistencia, reglas de alerta y comunicación entre API y frontend; además, validé los flujos funcionales y depuré inconsistencias.",
      en: "I designed and structured the simulated telemetry flow from ingestion to querying and visualization. I integrated persistence, alert rules, and API-to-frontend communication, then validated functional workflows and debugged inconsistencies.",
    },
    learnings: [
      { es: "Modelado y consulta de telemetría.", en: "Telemetry modeling and querying." },
      { es: "Persistencia con PostgreSQL, Cassandra y MongoDB.", en: "Persistence with PostgreSQL, Cassandra, and MongoDB." },
      { es: "Desarrollo de APIs con FastAPI.", en: "API development with FastAPI." },
      { es: "Comunicación mediante Server-Sent Events.", en: "Communication through Server-Sent Events." },
      { es: "Visualización con mapas y gráficos.", en: "Visualization with maps and charts." },
      { es: "Aplicación de reglas sobre datos operativos.", en: "Applying rules to operational data." },
    ],
    techStack: ["Python", "FastAPI", "React", "PostgreSQL", "Apache Cassandra", "MongoDB", "Docker Compose", "Server-Sent Events", "Leaflet", "Recharts"],
    coverImage: "/projects/smartfleet-v2/cover.jpg",
    links: {
      repository: "https://github.com/juanj983009-eng/SMARTFLEET_V2",
      video: "https://youtu.be/GWb8TBxducY",
    },
    screenshots: [
      "/projects/smartfleet-v2/gallery/captura-de-pantalla-2026-07-28-232338.png",
      "/projects/smartfleet-v2/gallery/captura-de-pantalla-2026-07-28-232352.png",
      "/projects/smartfleet-v2/gallery/captura-de-pantalla-2026-07-28-232402.png",
      "/projects/smartfleet-v2/gallery/captura-de-pantalla-2026-07-28-232412.png",
      "/projects/smartfleet-v2/gallery/captura-de-pantalla-2026-07-28-232422.png",
      "/projects/smartfleet-v2/gallery/captura-de-pantalla-2026-07-28-232431.png",
      "/projects/smartfleet-v2/gallery/captura-de-pantalla-2026-07-28-232438.png",
      "/projects/smartfleet-v2/gallery/captura-de-pantalla-2026-07-28-232446.png",
      "/projects/smartfleet-v2/gallery/captura-de-pantalla-2026-07-28-232501.png",
      "/projects/smartfleet-v2/gallery/captura-de-pantalla-2026-07-28-232510.png",
    ],
    isFeatured: true
  },
  {
    id: "controller-production",
    slug: "controller-production",
    title: "Meca-PRO MES",
    category: { es: "PROYECTO PERSONAL", en: "PERSONAL PROJECT" },
    projectCategory: "personal",
    status: "functional",
    subtitle: {
      es: "Organiza órdenes y hojas de proceso para registrar producción, tiempos, paradas, recursos y costos en un entorno industrial simulado. Conecta flujos operativos con APIs, persistencia relacional e interfaces de seguimiento.",
      en: "Organizes work orders and process sheets to record production, time, downtime, resources, and costs in a simulated industrial environment. It connects operational workflows with APIs, relational persistence, and tracking interfaces.",
    },
    tagline: {
      es: "Organiza órdenes y hojas de proceso para registrar producción, tiempos, paradas, recursos y costos en un entorno industrial simulado. Conecta flujos operativos con APIs, persistencia relacional e interfaces de seguimiento.",
      en: "Organizes work orders and process sheets to record production, time, downtime, resources, and costs in a simulated industrial environment. It connects operational workflows with APIs, relational persistence, and tracking interfaces.",
    },
    description: {
      es: "Organiza órdenes y hojas de proceso para registrar producción, tiempos, paradas, recursos y costos en un entorno industrial simulado. Conecta flujos operativos con APIs, persistencia relacional e interfaces de seguimiento.",
      en: "Organizes work orders and process sheets to record production, time, downtime, resources, and costs in a simulated industrial environment. It connects operational workflows with APIs, relational persistence, and tracking interfaces.",
    },
    details: {
      es: "Meca-PRO MES modela flujos de gestión industrial para registrar hojas de proceso, producción, tiempos de actividad, paradas técnicas, recursos y costos. Los usuarios autenticados pueden consultar procesos, registrar cantidades aceptadas y rechazadas, iniciar o finalizar actividades y paradas, solicitar recursos y revisar costos. El backend utiliza Spring Boot, PostgreSQL, JPA y migraciones Flyway; la interfaz React consume sus APIs mediante paneles y formularios operativos. El sistema convierte procesos industriales conocidos en entidades, reglas y flujos de software dentro de un escenario simulado.",
      en: "Meca-PRO MES models industrial-management workflows for recording process sheets, production, activity time, technical downtime, resources, and costs. Authenticated users can consult processes, record accepted and rejected quantities, start or finish activities and downtime, request resources, and review costs. The backend uses Spring Boot, PostgreSQL, JPA, and Flyway migrations, while the React interface consumes its APIs through operational dashboards and forms. The system translates familiar industrial processes into software entities, rules, and workflows within a simulated scenario.",
    },
    contribution: {
      es: "Diseñé flujos de software a partir de procesos industriales, órdenes y operaciones. Integré frontend, APIs, autenticación y persistencia para gestionar hojas de proceso, tiempos, paradas, recursos y costos; también validé reglas y corregí comportamientos funcionales.",
      en: "I designed software workflows based on industrial processes, work orders, and operations. I integrated the frontend, APIs, authentication, and persistence for managing process sheets, time, downtime, resources, and costs, while validating rules and correcting functional behavior.",
    },
    learnings: [
      { es: "Modelado de procesos y entidades operativas.", en: "Modeling processes and operational entities." },
      { es: "APIs REST con Java y Spring Boot.", en: "REST APIs with Java and Spring Boot." },
      { es: "Persistencia relacional con PostgreSQL.", en: "Relational persistence with PostgreSQL." },
      { es: "Migraciones con Flyway.", en: "Migrations with Flyway." },
      { es: "Autenticación mediante JWT.", en: "JWT-based authentication." },
      { es: "Integración de seguimiento operativo y costos.", en: "Integration of operational tracking and costs." },
    ],
    techStack: ["Java", "Spring Boot", "Spring Data JPA", "Spring Security", "JWT", "PostgreSQL", "Flyway", "React", "Axios", "Docker Compose", "Nginx", "Maven"],
    coverImage: "/projects/controller-production/cover.jpg",
    links: {
      repository: "https://github.com/juanj983009-eng/Mecapro-mes-V1",
      video: "https://youtu.be/V4FemFCJsPg",
    },
    screenshots: [
      "/projects/controller-production/gallery/captura-de-pantalla-2026-07-29-082302.png",
      "/projects/controller-production/gallery/captura-de-pantalla-2026-07-29-082803.png",
      "/projects/controller-production/gallery/captura-de-pantalla-2026-07-29-082813.png",
      "/projects/controller-production/gallery/captura-de-pantalla-2026-07-29-082820.png",
      "/projects/controller-production/gallery/captura-de-pantalla-2026-07-29-082830.png",
      "/projects/controller-production/gallery/captura-de-pantalla-2026-07-29-082840.png",
      "/projects/controller-production/gallery/captura-de-pantalla-2026-07-29-082848.png",
      "/projects/controller-production/gallery/captura-de-pantalla-2026-07-29-082931.png",
      "/projects/controller-production/gallery/captura-de-pantalla-2026-07-29-082939.png",
      "/projects/controller-production/gallery/captura-de-pantalla-2026-07-29-082947.png",
      "/projects/controller-production/gallery/captura-de-pantalla-2026-07-29-083007.png",
      "/projects/controller-production/gallery/captura-de-pantalla-2026-07-29-083018.png",
      "/projects/controller-production/gallery/captura-de-pantalla-2026-07-29-083024.png",
      "/projects/controller-production/gallery/captura-de-pantalla-2026-07-29-083036.png",
      "/projects/controller-production/gallery/captura-de-pantalla-2026-07-29-083042.png",
    ],
    isFeatured: true
  },
  {
    id: "logicore-port-control",
    slug: "logicore-port-control",
    title: "LogiCore Port Control",
    category: { es: "SISTEMAS Y OPERACIONES", en: "SYSTEMS & OPERATIONS" },
    projectCategory: "academic",
    status: "functional",
    description: {
      es: "Aplicación logística con tres servicios Java que registra contenedores, organiza asignaciones mediante una cola FIFO y estructuras de datos manuales, conserva trazabilidad de eventos y presenta un dashboard con datos de PostgreSQL y SQL Server.",
      en: "Logistics application with three Java services that records containers, organizes assignments through a FIFO queue and manual data structures, preserves event traceability, and presents a dashboard backed by PostgreSQL and SQL Server data.",
    },
    details: {
      es: "LogiCore Port Control es una aplicación de logística simulada compuesta por tres servicios Java. Permite registrar contenedores, gestionar asignaciones mediante una cola FIFO y consultar eventos de auditoría. El proyecto incorpora estructuras de datos implementadas manualmente para modelar operaciones y utiliza PostgreSQL y SQL Server para persistir información de trabajo. Un dashboard integra las consultas y la visualización del estado de los registros. Su alcance se concentra en flujos simulados y demostraciones locales.",
      en: "LogiCore Port Control is a simulated logistics application composed of three Java services. It registers containers, manages assignments through a FIFO queue, and provides audit-event queries. The project uses manually implemented data structures to model operations, with PostgreSQL and SQL Server storing working data. A dashboard brings queries and record-status visualization together. Its scope focuses on simulated flows and local demonstrations.",
    },
    techStack: ["Java 21", "Spring Boot 3.x", "PostgreSQL", "SQL Server", "JavaScript", "Three.js", "Docker Compose", "Maven"],
    contribution: {
      es: "Diseñé las estructuras y flujos de asignación; integré los servicios Java, la persistencia y el dashboard; validé los recorridos funcionales y corregí inconsistencias.",
      en: "I designed the allocation structures and workflows; integrated the Java services, persistence, and dashboard; and validated functional journeys while correcting inconsistencies.",
    },
    learnings: [
      { es: "Registro y trazabilidad de contenedores y eventos.", en: "Container and event registration with traceability." },
      { es: "Implementación manual de una cola FIFO y estructuras de datos.", en: "Manual implementation of a FIFO queue and data structures." },
      { es: "Persistencia con PostgreSQL y SQL Server.", en: "Persistence with PostgreSQL and SQL Server." },
      { es: "Consulta y visualización de datos en un dashboard.", en: "Data querying and visualization in a dashboard." },
    ],
    coverImage: "/projects/logicore-port-control/cover.jpg",
    links: {
      repository: "https://github.com/juanj983009-eng/LogiCore-Port-Control",
      video: "https://youtu.be/2pPX6ErTX7A",
    },
    screenshots: [
      "/projects/logicore-port-control/gallery/captura-de-pantalla-2026-07-29-085803.png",
      "/projects/logicore-port-control/gallery/captura-de-pantalla-2026-07-29-085813.png",
      "/projects/logicore-port-control/gallery/captura-de-pantalla-2026-07-29-085818.png",
      "/projects/logicore-port-control/gallery/captura-de-pantalla-2026-07-29-085825.png",
      "/projects/logicore-port-control/gallery/captura-de-pantalla-2026-07-29-085837.png",
      "/projects/logicore-port-control/gallery/captura-de-pantalla-2026-07-29-085846.png",
      "/projects/logicore-port-control/gallery/captura-de-pantalla-2026-07-29-085856.png",
      "/projects/logicore-port-control/gallery/captura-de-pantalla-2026-07-29-085902.png",
      "/projects/logicore-port-control/gallery/captura-de-pantalla-2026-07-29-085909.png",
      "/projects/logicore-port-control/gallery/captura-de-pantalla-2026-07-29-085916.png",
    ],
    isFeatured: false
  },
  {
    id: "podcast-streaming-app",
    slug: "podcast-streaming-app",
    title: "Testigo Oculto",
    category: { es: "AUDIO Y GESTIÓN", en: "AUDIO & MANAGEMENT" },
    projectCategory: "experimental",
    status: "functional",
    description: {
      es: "Aplicación de audio con autenticación JWT y roles, que organiza episodios, habilita reproducción parcial, administra saldo interno y desbloqueos, conserva historial de actividad y visualiza formas de onda con WaveSurfer.js.",
      en: "Audio application with JWT authentication and roles that organizes episodes, enables partial playback, manages an internal balance and unlocks, keeps activity history, and visualizes waveforms with WaveSurfer.js.",
    },
    details: {
      es: "Testigo Oculto es una aplicación de audio que organiza episodios y controla su acceso mediante autenticación JWT y roles. La interfaz React permite reproducir segmentos, visualizar formas de onda con WaveSurfer.js, consultar historial y gestionar desbloqueos mediante un saldo interno. El backend Spring Boot expone la lógica de acceso y persistencia con JPA/Hibernate y PostgreSQL; Axios conecta la interfaz con la API. Docker Compose acompaña la configuración local. El proyecto trabaja con contenido de demostración y flujos de aplicación.",
      en: "Testigo Oculto is an audio application that organizes episodes and controls access through JWT authentication and roles. Its React interface supports segment playback, waveform visualization with WaveSurfer.js, history queries, and unlocks managed through an internal balance. The Spring Boot backend provides access logic and persistence with JPA/Hibernate and PostgreSQL, while Axios connects the interface to the API. Docker Compose supports local configuration. The project uses demonstration content and application workflows.",
    },
    techStack: ["React 19", "Vite", "Java 17", "Spring Boot", "Spring Security", "JWT", "JPA/Hibernate", "PostgreSQL", "Axios", "WaveSurfer.js", "Docker Compose"],
    contribution: {
      es: "Integré el flujo de audio y la interfaz; implementé el control de acceso y los desbloqueos; validé los recorridos de reproducción e historial.",
      en: "I integrated the audio flow and interface; implemented access control and unlocks; and validated playback and history journeys.",
    },
    learnings: [
      { es: "Autenticación JWT y control de acceso por roles.", en: "JWT authentication and role-based access control." },
      { es: "Reproducción parcial y visualización de formas de onda.", en: "Partial playback and waveform visualization." },
      { es: "Gestión de saldo interno, desbloqueos e historial.", en: "Internal balance, unlock, and history management." },
      { es: "Integración entre interfaz React y API Spring Boot.", en: "Integration between the React interface and Spring Boot API." },
    ],
    coverImage: "/projects/podcast-streaming-app/cover.jpg",
    links: {
      repository: "https://github.com/juanj983009-eng/testigo-oculto-v2",
      video: "https://youtu.be/trWjGSGqxXw",
    },
    screenshots: [
      "/projects/podcast-streaming-app/gallery/captura-de-pantalla-2026-07-29-092352.png",
      "/projects/podcast-streaming-app/gallery/captura-de-pantalla-2026-07-29-092640.png",
      "/projects/podcast-streaming-app/gallery/captura-de-pantalla-2026-07-29-095756.png",
      "/projects/podcast-streaming-app/gallery/captura-de-pantalla-2026-07-29-095802.png",
      "/projects/podcast-streaming-app/gallery/captura-de-pantalla-2026-07-29-095808.png",
      "/projects/podcast-streaming-app/gallery/captura-de-pantalla-2026-07-29-095814.png",
      "/projects/podcast-streaming-app/gallery/captura-de-pantalla-2026-07-29-095826.png",
      "/projects/podcast-streaming-app/gallery/captura-de-pantalla-2026-07-29-095831.png",
      "/projects/podcast-streaming-app/gallery/captura-de-pantalla-2026-07-29-095838.png",
      "/projects/podcast-streaming-app/gallery/captura-de-pantalla-2026-07-29-095847.png",
      "/projects/podcast-streaming-app/gallery/captura-de-pantalla-2026-07-29-095854.png",
      "/projects/podcast-streaming-app/gallery/captura-de-pantalla-2026-07-29-095902.png",
      "/projects/podcast-streaming-app/gallery/captura-de-pantalla-2026-07-29-095910.png",
      "/projects/podcast-streaming-app/gallery/captura-de-pantalla-2026-07-29-095920.png"
    ],
    isFeatured: false
  },
  {
    id: "saas-bodegas-pos",
    slug: "saas-bodegas-pos",
    title: "SaaS Bodegas",
    category: { es: "VENTAS E INVENTARIO", en: "SALES & INVENTORY" },
    projectCategory: "experimental",
    status: "functional",
    description: {
      es: "Sistema local de punto de venta que registra ventas, descuenta stock y conserva historial en IndexedDB. Incluye catálogo, carrito, código de barras, métodos de pago, comprobante y una cola de registros pendientes para sincronización posterior mediante una API compatible.",
      en: "Local point-of-sale system that records sales, decreases stock, and stores history in IndexedDB. It includes a catalog, cart, barcode lookup, payment methods, receipts, and a queue of pending records for later synchronization through a compatible API.",
    },
    details: {
      es: "SaaS Bodegas es un sistema local de punto de venta construido con React, TypeScript y una API NestJS. Gestiona productos, stock, ventas y estados de sincronización mediante IndexedDB en el navegador y PostgreSQL en el backend. Durante el cobro valida el stock disponible, descuenta unidades y registra la venta localmente; las operaciones pendientes se conservan en una cola para sincronización posterior mediante una API compatible. Incluye catálogo, carrito, registro rápido de productos, historial y consultas de métricas. Docker Compose acompaña la configuración del entorno local.",
      en: "SaaS Bodegas is a local point-of-sale system built with React, TypeScript, and a NestJS API. It manages products, stock, sales, and synchronization states through browser IndexedDB and backend PostgreSQL. During checkout, it validates available stock, decreases units, and records the sale locally; pending operations remain in a queue for later synchronization through a compatible API. It includes a catalog, cart, quick product registration, history, and metrics queries. Docker Compose supports local environment configuration.",
    },
    techStack: ["React", "TypeScript", "Vite", "Dexie/IndexedDB", "NestJS", "Prisma", "PostgreSQL", "Playwright"],
    contribution: {
      es: "Implementé el flujo de cobro local con validación de stock y registro transaccional de ventas; modelé productos, ventas y líneas de venta; integré el POS con inventario, historial, métricas y colas de sincronización.",
      en: "I implemented the local checkout flow with stock validation and transactional sales records; modeled products, sales, and sale lines; and integrated the POS with inventory, history, metrics, and synchronization queues.",
    },
    learnings: [
      { es: "Gestión local de catálogo y stock.", en: "Local catalog and stock management." },
      { es: "Registro atómico de ventas en IndexedDB.", en: "Atomic sales recording in IndexedDB." },
      { es: "Cola FIFO de operaciones pendientes de sincronización.", en: "FIFO queue for pending synchronization operations." },
      { es: "Modelado relacional de ventas e inventario con Prisma y PostgreSQL.", en: "Relational sales and inventory modeling with Prisma and PostgreSQL." },
      { es: "Consultas de métricas de ventas y productos desde la API.", en: "Sales and product metric queries through the API." },
    ],
    coverImage: "/projects/saas-bodegas-pos/cover.jpg",
    links: {
      video: "https://youtu.be/oDbNjL_c7dI",
    },
    screenshots: [
      "/projects/saas-bodegas-pos/gallery/captura-de-pantalla-2026-07-29-104359.png",
      "/projects/saas-bodegas-pos/gallery/captura-de-pantalla-2026-07-29-104406.png",
      "/projects/saas-bodegas-pos/gallery/captura-de-pantalla-2026-07-29-104421.png",
      "/projects/saas-bodegas-pos/gallery/captura-de-pantalla-2026-07-29-104430.png",
      "/projects/saas-bodegas-pos/gallery/captura-de-pantalla-2026-07-29-104438.png",
      "/projects/saas-bodegas-pos/gallery/captura-de-pantalla-2026-07-29-104443.png",
      "/projects/saas-bodegas-pos/gallery/captura-de-pantalla-2026-07-29-104454.png",
      "/projects/saas-bodegas-pos/gallery/captura-de-pantalla-2026-07-29-104507.png",
      "/projects/saas-bodegas-pos/gallery/captura-de-pantalla-2026-07-29-104512.png",
      "/projects/saas-bodegas-pos/gallery/captura-de-pantalla-2026-07-29-104534.png",
      "/projects/saas-bodegas-pos/gallery/captura-de-pantalla-2026-07-29-104546.png",
    ],
    isFeatured: false
  },
  {
    id: "tienda-catys",
    slug: "tienda-catys",
    title: "Tienda Catys",
    category: { es: "PROYECTO ACADÉMICO", en: "ACADEMIC PROJECT" },
    projectCategory: "academic",
    status: "functional",
    subtitle: {
      es: "Centraliza pedidos, productos, mesas, inventario y comandas dentro de un flujo de gestión gastronómica. Registra ventas, actualiza existencias y genera información para dashboards y reportes mediante React, APIs Java y SQL Server.",
      en: "Centralizes orders, products, tables, inventory, and kitchen tickets within a restaurant-management workflow. It records sales, updates stock, and generates dashboard and reporting information through React, Java APIs, and SQL Server.",
    },
    tagline: {
      es: "Centraliza pedidos, productos, mesas, inventario y comandas dentro de un flujo de gestión gastronómica. Registra ventas, actualiza existencias y genera información para dashboards y reportes mediante React, APIs Java y SQL Server.",
      en: "Centralizes orders, products, tables, inventory, and kitchen tickets within a restaurant-management workflow. It records sales, updates stock, and generates dashboard and reporting information through React, Java APIs, and SQL Server.",
    },
    description: {
      es: "Centraliza pedidos, productos, mesas, inventario y comandas dentro de un flujo de gestión gastronómica. Registra ventas, actualiza existencias y genera información para dashboards y reportes mediante React, APIs Java y SQL Server.",
      en: "Centralizes orders, products, tables, inventory, and kitchen tickets within a restaurant-management workflow. It records sales, updates stock, and generates dashboard and reporting information through React, Java APIs, and SQL Server.",
    },
    details: {
      es: "Tienda Catys organiza el flujo gastronómico desde la selección de productos hasta el registro de la venta y generación de comandas para cocina. La aplicación gestiona mesas, clientes, productos, insumos e inventario; al confirmar una venta, conserva el detalle y actualiza existencias. También incorpora vistas para pedidos de cocina, dashboard y reportes financieros. El backend combina Spring Boot, JPA, JDBC y SQL Server, mientras que React presenta las operaciones mediante formularios, paneles y consultas a APIs.",
      en: "Tienda Catys organizes restaurant workflows from product selection to sales registration and kitchen-ticket generation. The application manages tables, customers, products, supplies, and inventory; when a sale is confirmed, it stores transaction details and updates stock. It also includes kitchen-order, dashboard, and financial-report views. The backend combines Spring Boot, JPA, JDBC, and SQL Server, while React presents operations through forms, dashboards, and API queries.",
    },
    contribution: {
      es: "Diseñé y modelé los flujos de pedidos, ventas, mesas, productos e inventario. Integré React con APIs Java y persistencia relacional; además, validé ventas, actualización de stock, generación de comandas y pantallas de seguimiento.",
      en: "I designed and modeled workflows for orders, sales, tables, products, and inventory. I integrated React with Java APIs and relational persistence, then validated sales, stock updates, kitchen-ticket generation, and tracking views.",
    },
    learnings: [
      { es: "Modelado de ventas e inventario.", en: "Sales and inventory modeling." },
      { es: "Persistencia relacional con SQL Server.", en: "Relational persistence with SQL Server." },
      { es: "Integración entre React y APIs REST.", en: "Integration between React and REST APIs." },
      { es: "Consultas para dashboards y reportes.", en: "Queries for dashboards and reports." },
      { es: "Gestión de mesas, comandas y existencias.", en: "Management of tables, kitchen tickets, and stock." },
    ],
    techStack: ["Java", "Spring Boot", "Spring Data JPA", "JDBC", "SQL Server", "React", "Vite", "Tailwind CSS", "Docker Compose", "REST APIs"],
    coverImage: "/projects/tienda-catys/cover.jpg",
    links: {
      repository: "https://github.com/juanj983009-eng/Tienda-Catys-Java",
      video: "https://youtu.be/jEqSSWqL214",
    },
    screenshots: [
      "/projects/tienda-catys/gallery/captura-de-pantalla-2026-08-07-151919.png",
      "/projects/tienda-catys/gallery/captura-de-pantalla-2026-08-07-151957.png",
      "/projects/tienda-catys/gallery/captura-de-pantalla-2026-08-07-152003.png",
      "/projects/tienda-catys/gallery/captura-de-pantalla-2026-08-07-152010.png",
      "/projects/tienda-catys/gallery/captura-de-pantalla-2026-08-07-152019.png",
      "/projects/tienda-catys/gallery/captura-de-pantalla-2026-08-07-152026.png",
      "/projects/tienda-catys/gallery/captura-de-pantalla-2026-08-07-152050.png",
      "/projects/tienda-catys/gallery/captura-de-pantalla-2026-08-07-152101.png",
      "/projects/tienda-catys/gallery/captura-de-pantalla-2026-08-07-152109.png",
      "/projects/tienda-catys/gallery/captura-de-pantalla-2026-08-07-152116.png",
      "/projects/tienda-catys/gallery/captura-de-pantalla-2026-08-07-152122.png",
      "/projects/tienda-catys/gallery/captura-de-pantalla-2026-08-07-152128.png",
      "/projects/tienda-catys/gallery/captura-de-pantalla-2026-08-07-152135.png",
      "/projects/tienda-catys/gallery/captura-de-pantalla-2026-08-07-152141.png",
      "/projects/tienda-catys/gallery/captura-de-pantalla-2026-08-07-152150.png"
    ],
    isFeatured: true
  },
  {
    id: "biblioteca-digital",
    slug: "biblioteca-digital",
    title: "Biblioteca Digital",
    category: { es: "CATÁLOGO Y COMERCIO", en: "CATALOG & COMMERCE" },
    projectCategory: "experimental",
    status: "functional",
    description: {
      es: "Aplicación de catálogo digital que permite buscar y filtrar libros, añadirlos al carrito y completar un checkout simulado. Integra inventario, persistencia PostgreSQL, caché Redis, API Java y pruebas de integración.",
      en: "Digital catalog application that lets users search and filter books, add them to a cart, and complete a simulated checkout. It integrates inventory, PostgreSQL persistence, Redis caching, a Java API, and integration tests.",
    },
    details: {
      es: "Biblioteca Digital es una aplicación web para explorar un catálogo, aplicar búsquedas y filtros, seleccionar títulos y completar un flujo de carrito y checkout simulado. La API Java gestiona el inventario y la persistencia en PostgreSQL, mientras Redis se incorpora para caché. El frontend Next.js presenta la navegación y selección de libros. El repositorio incluye pruebas de integración para los flujos de backend. Resilience4j se utiliza como patrón de contingencia explorado para llamadas entre componentes, sin convertirlo en una garantía operativa. Los títulos, ratings, reseñas y datos del catálogo se usan como contenido de demostración.",
      en: "Biblioteca Digital is a web application for exploring a catalog, applying searches and filters, selecting titles, and completing a simulated cart and checkout flow. Its Java API manages inventory and PostgreSQL persistence, while Redis is used for caching. The Next.js frontend presents book navigation and selection. The repository includes integration tests for backend flows. Resilience4j is explored as a contingency pattern for calls between components, without presenting an operational guarantee. Titles, ratings, reviews, and catalog data are demonstration content.",
    },
    techStack: [
      "Java 17",
      "Spring Boot 3.3",
      "Next.js 16 (App Router)",
      "React 19",
      "TypeScript",
      "PostgreSQL 16",
      "Redis 7",
      "Spring Data JPA / Hibernate",
      "Resilience4j",
      "TailwindCSS",
      "Three.js",
      "React Three Fiber",
      "Docker",
      "Docker Compose",
      "JUnit 5 / Testcontainers"
    ],
    contribution: {
      es: "Integré catálogo, navegación y carrito; conecté inventario y persistencia con la API Java; validé los flujos mediante pruebas de integración.",
      en: "I integrated the catalog, navigation, and cart; connected inventory and persistence through the Java API; and validated flows with integration tests.",
    },
    learnings: [
      { es: "Búsqueda, filtros y navegación de catálogos.", en: "Catalog search, filtering, and navigation." },
      { es: "Gestión de carrito, checkout simulado e inventario.", en: "Cart, simulated checkout, and inventory management." },
      { es: "Persistencia con PostgreSQL y caché con Redis.", en: "PostgreSQL persistence and Redis caching." },
      { es: "Pruebas de integración y patrones de contingencia explorados.", en: "Integration testing and explored contingency patterns." },
    ],
    coverImage: "/projects/biblioteca-digital/cover.jpg",
    links: {
      repository: "https://github.com/juanj983009-eng/Libreria-Digital",
      video: "https://youtu.be/-wGJQhYD_iI",
    },
    screenshots: [
      "/projects/biblioteca-digital/gallery/captura-de-pantalla-2026-07-29-160125.png",
      "/projects/biblioteca-digital/gallery/captura-de-pantalla-2026-07-29-160131.png",
      "/projects/biblioteca-digital/gallery/captura-de-pantalla-2026-07-29-160142.png",
      "/projects/biblioteca-digital/gallery/captura-de-pantalla-2026-07-29-160150.png",
      "/projects/biblioteca-digital/gallery/captura-de-pantalla-2026-07-29-160159.png",
      "/projects/biblioteca-digital/gallery/captura-de-pantalla-2026-07-29-160212.png",
      "/projects/biblioteca-digital/gallery/captura-de-pantalla-2026-07-29-160225.png",
      "/projects/biblioteca-digital/gallery/captura-de-pantalla-2026-07-29-160236.png",
      "/projects/biblioteca-digital/gallery/captura-de-pantalla-2026-07-29-160241.png",
      "/projects/biblioteca-digital/gallery/captura-de-pantalla-2026-07-29-160251.png",
      "/projects/biblioteca-digital/gallery/captura-de-pantalla-2026-07-29-160256.png",
      "/projects/biblioteca-digital/gallery/captura-de-pantalla-2026-07-29-160302.png"
    ],
    isFeatured: false
  },
  {
    id: "clinicav2-stack",
    slug: "clinicav2-stack",
    title: "HealthTech 2026",
    category: { es: "DATOS Y VISUALIZACIÓN", en: "DATA & VISUALIZATION" },
    projectCategory: "academic",
    status: "functional",
    description: {
      es: "Aplicación de visualización de datos sintéticos que organiza perfiles y camas simuladas, muestra tarjetas, alertas y tendencias, y actualiza la interfaz mediante Server-Sent Events con persistencia en PostgreSQL.",
      en: "Synthetic-data visualization application that organizes simulated profiles and beds, displays cards, alerts, and trends, and updates the interface through Server-Sent Events with PostgreSQL persistence.",
    },
    details: {
      es: "HealthTech 2026 es una aplicación de visualización que trabaja exclusivamente con perfiles, camas y señales sintéticas. El backend Java gestiona la persistencia en PostgreSQL y publica actualizaciones mediante Server-Sent Events; la interfaz React presenta tarjetas, alertas y tendencias para explorar cambios en los datos simulados. El proyecto permite modelar flujos de interfaz y actualización continua dentro de un escenario de demostración. No procesa pacientes, dispositivos, historias clínicas ni información clínica real, y no toma decisiones médicas.",
      en: "HealthTech 2026 is a visualization application that works exclusively with synthetic profiles, beds, and signals. The Java backend manages PostgreSQL persistence and publishes updates through Server-Sent Events; the React interface presents cards, alerts, and trends to explore changes in simulated data. The project models interface flows and continuous updates within a demonstration scenario. It does not process real patients, devices, medical records, or clinical information, and it does not make medical decisions.",
    },
    techStack: [
      "Java 17",
      "Spring Boot 3.x",
      "Spring Data JPA",
      "React 19",
      "TypeScript",
      "PostgreSQL 15",
      "Nginx Proxy",
      "Docker",
      "Docker Compose",
      "Server-Sent Events (SSE)",
      "Tailwind CSS",
      "Lucide React"
    ],
    contribution: {
      es: "Modelé los flujos de datos sintéticos; integré la actualización por SSE con la interfaz; validé tarjetas, alertas y tendencias visuales.",
      en: "I modeled synthetic-data flows; integrated SSE updates with the interface; and validated cards, alerts, and visual trends.",
    },
    learnings: [
      { es: "Modelado y visualización de datos sintéticos.", en: "Synthetic-data modeling and visualization." },
      { es: "Actualización de interfaces mediante Server-Sent Events.", en: "Interface updates through Server-Sent Events." },
      { es: "Presentación de tarjetas, alertas y tendencias.", en: "Presentation of cards, alerts, and trends." },
      { es: "Persistencia relacional con PostgreSQL.", en: "Relational persistence with PostgreSQL." },
    ],
    coverImage: "/projects/clinicav2-stack/cover.jpg",
    links: {
      repository: "https://github.com/juanj983009-eng/Clinica_V2",
      video: "https://youtu.be/xR0LZ8JPsU0",
    },
    screenshots: [
      "/projects/clinicav2-stack/gallery/captura-de-pantalla-2026-07-29-161811.png",
      "/projects/clinicav2-stack/gallery/captura-de-pantalla-2026-07-29-161816.png",
      "/projects/clinicav2-stack/gallery/captura-de-pantalla-2026-07-29-161822.png",
      "/projects/clinicav2-stack/gallery/captura-de-pantalla-2026-07-29-161828.png",
      "/projects/clinicav2-stack/gallery/captura-de-pantalla-2026-07-29-161833.png",
      "/projects/clinicav2-stack/gallery/captura-de-pantalla-2026-07-29-161840.png",
      "/projects/clinicav2-stack/gallery/captura-de-pantalla-2026-07-29-161844.png",
      "/projects/clinicav2-stack/gallery/captura-de-pantalla-2026-07-29-161851.png",
      "/projects/clinicav2-stack/gallery/captura-de-pantalla-2026-07-29-161858.png",
      "/projects/clinicav2-stack/gallery/captura-de-pantalla-2026-07-29-161903.png",
      "/projects/clinicav2-stack/gallery/captura-de-pantalla-2026-07-29-161913.png",
      "/projects/clinicav2-stack/gallery/captura-de-pantalla-2026-07-29-161918.png",
      "/projects/clinicav2-stack/gallery/captura-de-pantalla-2026-07-29-161927.png"
    ],
    isFeatured: false
  },
  {
    id: "olimpiadas-peru",
    slug: "olimpiadas-peru",
    title: "Olimpiadas Perú 2026",
    category: { es: "GESTIÓN Y RESULTADOS", en: "MANAGEMENT & RESULTS" },
    projectCategory: "academic",
    status: "functional",
    description: {
      es: "Aplicación de gestión deportiva simulada que administra participantes y competencias, valida reglas horarias, registra resultados, calcula podios y medallero, y presenta indicadores con PostgreSQL, Jakarta Servlets, JDBC y Chart.js.",
      en: "Simulated sports-management application that manages participants and competitions, validates scheduling rules, records results, calculates podiums and medal tables, and presents indicators with PostgreSQL, Jakarta Servlets, JDBC, and Chart.js.",
    },
    details: {
      es: "Olimpiadas Perú 2026 es una aplicación de gestión deportiva simulada para administrar participantes, competencias y resultados. Implementa reglas horarias para programar actividades, registra resultados y calcula podios y medallero. El backend utiliza Jakarta Servlets y JDBC con PostgreSQL; la interfaz JavaScript incorpora gráficos con Chart.js para visualizar indicadores. Docker Compose acompaña la configuración local. Países, sedes, cronogramas y resultados incluidos son datos de demostración: el proyecto no representa un evento oficial, federaciones ni resultados en vivo.",
      en: "Olimpiadas Perú 2026 is a simulated sports-management application for administering participants, competitions, and results. It implements scheduling rules for activities, records results, and calculates podiums and medal tables. The backend uses Jakarta Servlets and JDBC with PostgreSQL, while the JavaScript interface includes Chart.js charts to visualize indicators. Docker Compose supports local configuration. Included countries, venues, schedules, and results are demonstration data; the project does not represent an official event, federations, or live results.",
    },
    techStack: [
      "Java 17",
      "Jakarta Servlets",
      "Apache Tomcat 10",
      "PostgreSQL 15",
      "Docker & Docker Compose",
      "HikariCP",
      "JavaScript (ES6+)",
      "Chart.js",
      "HTML5",
      "CSS3 / Design Tokens",
      "Bootstrap 5",
      "Maven"
    ],
    contribution: {
      es: "Modelé los flujos de participantes y competencias; implementé reglas de programación, podios y medallero; integré la persistencia y los indicadores visuales.",
      en: "I modeled participant and competition workflows; implemented scheduling rules, podiums, and medal tables; and integrated persistence with visual indicators.",
    },
    learnings: [
      { es: "Gestión de participantes, competencias y resultados.", en: "Participant, competition, and result management." },
      { es: "Validación de reglas horarias y programación.", en: "Scheduling-rule validation and programming." },
      { es: "Cálculo de podios y medallero.", en: "Podium and medal-table calculation." },
      { es: "Persistencia con PostgreSQL y visualización con Chart.js.", en: "PostgreSQL persistence and Chart.js visualization." },
    ],
    coverImage: "/projects/olimpiadas-peru/cover.jpg",
    links: {
      repository: "https://github.com/juanj983009-eng/Olimpiadas-Peru",
      video: "https://youtu.be/KbHmRWK1-ws",
    },
    screenshots: [
      "/projects/olimpiadas-peru/gallery/captura-de-pantalla-2026-07-29-163441.png",
      "/projects/olimpiadas-peru/gallery/captura-de-pantalla-2026-07-29-163449.png",
      "/projects/olimpiadas-peru/gallery/captura-de-pantalla-2026-07-29-163455.png",
      "/projects/olimpiadas-peru/gallery/captura-de-pantalla-2026-07-29-163502.png",
      "/projects/olimpiadas-peru/gallery/captura-de-pantalla-2026-07-29-163509.png",
      "/projects/olimpiadas-peru/gallery/captura-de-pantalla-2026-07-29-163516.png",
      "/projects/olimpiadas-peru/gallery/captura-de-pantalla-2026-07-29-163523.png",
      "/projects/olimpiadas-peru/gallery/captura-de-pantalla-2026-07-29-163531.png",
      "/projects/olimpiadas-peru/gallery/captura-de-pantalla-2026-07-29-163541.png",
      "/projects/olimpiadas-peru/gallery/captura-de-pantalla-2026-07-29-163550.png",
      "/projects/olimpiadas-peru/gallery/captura-de-pantalla-2026-07-29-163602.png"
    ],
    isFeatured: false
  }
];

export default PROJECTS;
