import { Project } from "@/types/portfolio";

export const PROJECTS: Project[] = [
  {
    id: "smartfleet-v2",
    slug: "smartfleet-v2",
    title: "SMARTFLEET V2",
    category: { es: "PROYECTO PERSONAL", en: "PERSONAL PROJECT" },
    projectCategory: "personal",
    status: "functional",
    subtitle: {
      es: "Centraliza telemetría simulada de flotas para registrar señales operativas, consultar historiales, generar alertas mediante reglas y visualizar resultados en mapas y paneles. Integra diferentes modelos de almacenamiento para analizar vehículos, conductores e incidentes.",
      en: "Centralizes simulated fleet telemetry to record operational signals, query historical data, generate rule-based alerts, and visualize results through maps and dashboards. It integrates different storage models to analyze vehicles, drivers, and incidents.",
    },
    tagline: {
      es: "Centraliza telemetría simulada de flotas para registrar señales operativas, consultar historiales, generar alertas mediante reglas y visualizar resultados en mapas y paneles. Integra diferentes modelos de almacenamiento para analizar vehículos, conductores e incidentes.",
      en: "Centralizes simulated fleet telemetry to record operational signals, query historical data, generate rule-based alerts, and visualize results through maps and dashboards. It integrates different storage models to analyze vehicles, drivers, and incidents.",
    },
    description: {
      es: "Centraliza telemetría simulada de flotas para registrar señales operativas, consultar historiales, generar alertas mediante reglas y visualizar resultados en mapas y paneles. Integra diferentes modelos de almacenamiento para analizar vehículos, conductores e incidentes.",
      en: "Centralizes simulated fleet telemetry to record operational signals, query historical data, generate rule-based alerts, and visualize results through maps and dashboards. It integrates different storage models to analyze vehicles, drivers, and incidents.",
    },
    details: {
      es: "SmartFleet V2 organiza datos simulados de telemetría para visualizar el estado de vehículos y analizar eventos operativos. Recibe ubicación, velocidad, combustible, RPM y temperatura; almacena las lecturas en Cassandra, consulta vehículos y umbrales en PostgreSQL y registra alertas e incidentes en MongoDB. El backend expone endpoints de ingesta, análisis, consultas y actualizaciones mediante Server-Sent Events. La interfaz React presenta mapas, gráficos e historiales que conectan almacenamiento, reglas de negocio y visualización de datos dentro de un escenario logístico simulado.",
      en: "SmartFleet V2 organizes simulated telemetry data to visualize vehicle status and analyze operational events. It receives location, speed, fuel, RPM, and temperature readings; stores telemetry in Cassandra, queries vehicles and thresholds in PostgreSQL, and records alerts and incidents in MongoDB. The backend exposes ingestion, analysis, query, and Server-Sent Events endpoints. The React interface provides maps, charts, and historical views connecting storage, business rules, and data visualization within a simulated logistics scenario.",
    },
    contribution: {
      es: "Diseñé y estructuré el flujo de telemetría simulada desde la ingesta hasta la consulta y visualización. Integré persistencia, reglas de alerta y comunicación entre API y frontend; además, validé los flujos funcionales y depuré inconsistencias.",
      en: "I designed and structured the simulated telemetry flow from ingestion to querying and visualization. I integrated persistence, alert rules, and API-to-frontend communication, then validated functional workflows and debugged inconsistencies.",
    },
    learnings: [
      { es: "Modelado y consulta de telemetría.", en: "Telemetry modeling and querying." },
      { es: "Persistencia con PostgreSQL, Cassandra y MongoDB.", en: "Persistence with PostgreSQL, Cassandra, and MongoDB." },
      { es: "Desarrollo de APIs con FastAPI.", en: "API development with FastAPI." },
      { es: "Comunicación mediante Server-Sent Events.", en: "Communication through Server-Sent Events." },
      { es: "Visualización con mapas y gráficos.", en: "Visualization with maps and charts." },
      { es: "Aplicación de reglas sobre datos operativos.", en: "Applying rules to operational data." },
    ],
    techStack: ["Python", "FastAPI", "React", "PostgreSQL", "Apache Cassandra", "MongoDB", "Docker Compose", "Server-Sent Events", "Leaflet", "Recharts"],
    coverImage: "/projects/smartfleet-v2/cover.jpg",
    links: {
      repository: "https://github.com/juanj983009-eng/SMARTFLEET_V2",
      video: "https://youtu.be/GWb8TBxducY",
    },
    screenshots: [
      "/projects/smartfleet-v2/gallery/captura-de-pantalla-2026-07-28-232338.png",
      "/projects/smartfleet-v2/gallery/captura-de-pantalla-2026-07-28-232352.png",
      "/projects/smartfleet-v2/gallery/captura-de-pantalla-2026-07-28-232402.png",
      "/projects/smartfleet-v2/gallery/captura-de-pantalla-2026-07-28-232412.png",
      "/projects/smartfleet-v2/gallery/captura-de-pantalla-2026-07-28-232422.png",
      "/projects/smartfleet-v2/gallery/captura-de-pantalla-2026-07-28-232431.png",
      "/projects/smartfleet-v2/gallery/captura-de-pantalla-2026-07-28-232438.png",
      "/projects/smartfleet-v2/gallery/captura-de-pantalla-2026-07-28-232446.png",
      "/projects/smartfleet-v2/gallery/captura-de-pantalla-2026-07-28-232501.png",
      "/projects/smartfleet-v2/gallery/captura-de-pantalla-2026-07-28-232510.png",
    ],
    isFeatured: true
  },
  {
    id: "controller-production",
    slug: "controller-production",
    title: "Meca-PRO MES",
    category: { es: "PROYECTO PERSONAL", en: "PERSONAL PROJECT" },
    projectCategory: "personal",
    status: "functional",
    subtitle: {
      es: "Organiza órdenes y hojas de proceso para registrar producción, tiempos, paradas, recursos y costos en un entorno industrial simulado. Conecta flujos operativos con APIs, persistencia relacional e interfaces de seguimiento.",
      en: "Organizes work orders and process sheets to record production, time, downtime, resources, and costs in a simulated industrial environment. It connects operational workflows with APIs, relational persistence, and tracking interfaces.",
    },
    tagline: {
      es: "Organiza órdenes y hojas de proceso para registrar producción, tiempos, paradas, recursos y costos en un entorno industrial simulado. Conecta flujos operativos con APIs, persistencia relacional e interfaces de seguimiento.",
      en: "Organizes work orders and process sheets to record production, time, downtime, resources, and costs in a simulated industrial environment. It connects operational workflows with APIs, relational persistence, and tracking interfaces.",
    },
    description: {
      es: "Organiza órdenes y hojas de proceso para registrar producción, tiempos, paradas, recursos y costos en un entorno industrial simulado. Conecta flujos operativos con APIs, persistencia relacional e interfaces de seguimiento.",
      en: "Organizes work orders and process sheets to record production, time, downtime, resources, and costs in a simulated industrial environment. It connects operational workflows with APIs, relational persistence, and tracking interfaces.",
    },
    details: {
      es: "Meca-PRO MES modela flujos de gestión industrial para registrar hojas de proceso, producción, tiempos de actividad, paradas técnicas, recursos y costos. Los usuarios autenticados pueden consultar procesos, registrar cantidades aceptadas y rechazadas, iniciar o finalizar actividades y paradas, solicitar recursos y revisar costos. El backend utiliza Spring Boot, PostgreSQL, JPA y migraciones Flyway; la interfaz React consume sus APIs mediante paneles y formularios operativos. El sistema convierte procesos industriales conocidos en entidades, reglas y flujos de software dentro de un escenario simulado.",
      en: "Meca-PRO MES models industrial-management workflows for recording process sheets, production, activity time, technical downtime, resources, and costs. Authenticated users can consult processes, record accepted and rejected quantities, start or finish activities and downtime, request resources, and review costs. The backend uses Spring Boot, PostgreSQL, JPA, and Flyway migrations, while the React interface consumes its APIs through operational dashboards and forms. The system translates familiar industrial processes into software entities, rules, and workflows within a simulated scenario.",
    },
    contribution: {
      es: "Diseñé flujos de software a partir de procesos industriales, órdenes y operaciones. Integré frontend, APIs, autenticación y persistencia para gestionar hojas de proceso, tiempos, paradas, recursos y costos; también validé reglas y corregí comportamientos funcionales.",
      en: "I designed software workflows based on industrial processes, work orders, and operations. I integrated the frontend, APIs, authentication, and persistence for managing process sheets, time, downtime, resources, and costs, while validating rules and correcting functional behavior.",
    },
    learnings: [
      { es: "Modelado de procesos y entidades operativas.", en: "Modeling processes and operational entities." },
      { es: "APIs REST con Java y Spring Boot.", en: "REST APIs with Java and Spring Boot." },
      { es: "Persistencia relacional con PostgreSQL.", en: "Relational persistence with PostgreSQL." },
      { es: "Migraciones con Flyway.", en: "Migrations with Flyway." },
      { es: "Autenticación mediante JWT.", en: "JWT-based authentication." },
      { es: "Integración de seguimiento operativo y costos.", en: "Integration of operational tracking and costs." },
    ],
    techStack: ["Java", "Spring Boot", "Spring Data JPA", "Spring Security", "JWT", "PostgreSQL", "Flyway", "React", "Axios", "Docker Compose", "Nginx", "Maven"],
    coverImage: "/projects/controller-production/cover.jpg",
    links: {
      repository: "https://github.com/juanj983009-eng/Mecapro-mes-V1",
      video: "https://youtu.be/V4FemFCJsPg",
    },
    screenshots: [
      "/projects/controller-production/gallery/captura-de-pantalla-2026-07-29-082302.png",
      "/projects/controller-production/gallery/captura-de-pantalla-2026-07-29-082803.png",
      "/projects/controller-production/gallery/captura-de-pantalla-2026-07-29-082813.png",
      "/projects/controller-production/gallery/captura-de-pantalla-2026-07-29-082820.png",
      "/projects/controller-production/gallery/captura-de-pantalla-2026-07-29-082830.png",
      "/projects/controller-production/gallery/captura-de-pantalla-2026-07-29-082840.png",
      "/projects/controller-production/gallery/captura-de-pantalla-2026-07-29-082848.png",
      "/projects/controller-production/gallery/captura-de-pantalla-2026-07-29-082931.png",
      "/projects/controller-production/gallery/captura-de-pantalla-2026-07-29-082939.png",
      "/projects/controller-production/gallery/captura-de-pantalla-2026-07-29-082947.png",
      "/projects/controller-production/gallery/captura-de-pantalla-2026-07-29-083007.png",
      "/projects/controller-production/gallery/captura-de-pantalla-2026-07-29-083018.png",
      "/projects/controller-production/gallery/captura-de-pantalla-2026-07-29-083024.png",
      "/projects/controller-production/gallery/captura-de-pantalla-2026-07-29-083036.png",
      "/projects/controller-production/gallery/captura-de-pantalla-2026-07-29-083042.png",
    ],
    isFeatured: true
  },
  {
    id: "logicore-port-control",
    slug: "logicore-port-control",
    title: "LogiCore Port Control",
    category: { es: "PROYECTO ACADÉMICO", en: "ACADEMIC PROJECT" },
    projectCategory: "academic",
    status: "functional",
    subtitle: {
      es: "Prototipo académico para explorar lógica de asignación, estructuras de datos y visualización aplicadas a operaciones logísticas simuladas.",
      en: "Academic prototype exploring allocation logic, data structures, and visualization applied to simulated logistics operations.",
    },
    tagline: {
      es: "Prototipo académico para explorar lógica de asignación, estructuras de datos y visualización aplicadas a operaciones logísticas simuladas.",
      en: "Academic prototype exploring allocation logic, data structures, and visualization applied to simulated logistics operations.",
    },
    description: {
      es: "Prototipo académico para explorar lógica de asignación, estructuras de datos y visualización aplicadas a operaciones logísticas simuladas.",
      en: "Academic prototype exploring allocation logic, data structures, and visualization applied to simulated logistics operations.",
    },
    techStack: ["Java 17", "Spring Boot 3.x", "PostgreSQL 15", "MS SQL Server 2022", "Docker", "Docker Compose", "JavaScript (ES6+)", "Three.js", "JVM Concurrency", "Maven", "WSL2"],
    contribution: {
      es: "Trabajé en el análisis de los flujos, integración de componentes, pruebas funcionales y corrección del prototipo.",
      en: "I worked on workflow analysis, component integration, functional testing, and prototype corrections.",
    },
    learnings: [
      { es: "Aplicación de estructuras de datos a problemas logísticos.", en: "Applying data structures to logistics problems." },
      { es: "Modelado de operaciones y asignaciones.", en: "Modeling operations and assignments." },
      { es: "Integración de visualizaciones con datos simulados.", en: "Integrating visualizations with simulated data." },
    ],
    coverImage: "/projects/logicore-port-control/cover.jpg",
    links: {
      repository: "https://github.com/juanj983009-eng/LogiCore-Port-Control",
      video: "https://youtu.be/2pPX6ErTX7A",
    },
    screenshots: [
      "/projects/logicore-port-control/gallery/captura-de-pantalla-2026-07-29-085803.png",
      "/projects/logicore-port-control/gallery/captura-de-pantalla-2026-07-29-085813.png",
      "/projects/logicore-port-control/gallery/captura-de-pantalla-2026-07-29-085818.png",
      "/projects/logicore-port-control/gallery/captura-de-pantalla-2026-07-29-085825.png",
      "/projects/logicore-port-control/gallery/captura-de-pantalla-2026-07-29-085837.png",
      "/projects/logicore-port-control/gallery/captura-de-pantalla-2026-07-29-085846.png",
      "/projects/logicore-port-control/gallery/captura-de-pantalla-2026-07-29-085856.png",
      "/projects/logicore-port-control/gallery/captura-de-pantalla-2026-07-29-085902.png",
      "/projects/logicore-port-control/gallery/captura-de-pantalla-2026-07-29-085909.png",
      "/projects/logicore-port-control/gallery/captura-de-pantalla-2026-07-29-085916.png",
    ],
    isFeatured: false
  },
  {
    id: "podcast-streaming-app",
    slug: "podcast-streaming-app",
    title: "Testigo Oculto",
    category: { es: "PROYECTO EXPERIMENTAL", en: "EXPERIMENTAL PROJECT" },
    projectCategory: "experimental",
    status: "functional",
    subtitle: {
      es: "Prototipo experimental para gestionar y visualizar contenido de audio con autenticación y control de acceso.",
      en: "Experimental prototype for managing and visualizing audio content with authentication and access control.",
    },
    tagline: {
      es: "Prototipo experimental para gestionar y visualizar contenido de audio con autenticación y control de acceso.",
      en: "Experimental prototype for managing and visualizing audio content with authentication and access control.",
    },
    description: {
      es: "Prototipo experimental para gestionar y visualizar contenido de audio con autenticación y control de acceso.",
      en: "Experimental prototype for managing and visualizing audio content with authentication and access control.",
    },
    techStack: ["Java 17", "Spring Boot 3", "Spring Security", "JWT", "Spring Data JPA", "PostgreSQL", "React 18", "Vite", "Tailwind CSS", "Axios", "WaveSurfer.js", "Docker", "Docker Compose", "Maven"],
    contribution: {
      es: "Trabajé en la integración del flujo de audio, la interfaz, el control de acceso y las pruebas del prototipo.",
      en: "I worked on integrating the audio workflow, interface, access control, and prototype testing.",
    },
    learnings: [
      { es: "Reproducción y visualización de audio.", en: "Audio playback and visualization." },
      { es: "Autenticación y autorización.", en: "Authentication and authorization." },
      { es: "Manejo del estado de la interfaz.", en: "Interface state management." },
    ],
    coverImage: "/projects/podcast-streaming-app/cover.jpg",
    links: {
      repository: "https://github.com/juanj983009-eng/testigo-oculto-v2",
      video: "https://youtu.be/trWjGSGqxXw",
    },
    screenshots: [
      "/projects/podcast-streaming-app/gallery/captura-de-pantalla-2026-07-29-092352.png",
      "/projects/podcast-streaming-app/gallery/captura-de-pantalla-2026-07-29-092640.png",
      "/projects/podcast-streaming-app/gallery/captura-de-pantalla-2026-07-29-095756.png",
      "/projects/podcast-streaming-app/gallery/captura-de-pantalla-2026-07-29-095802.png",
      "/projects/podcast-streaming-app/gallery/captura-de-pantalla-2026-07-29-095808.png",
      "/projects/podcast-streaming-app/gallery/captura-de-pantalla-2026-07-29-095814.png",
      "/projects/podcast-streaming-app/gallery/captura-de-pantalla-2026-07-29-095826.png",
      "/projects/podcast-streaming-app/gallery/captura-de-pantalla-2026-07-29-095831.png",
      "/projects/podcast-streaming-app/gallery/captura-de-pantalla-2026-07-29-095838.png",
      "/projects/podcast-streaming-app/gallery/captura-de-pantalla-2026-07-29-095847.png",
      "/projects/podcast-streaming-app/gallery/captura-de-pantalla-2026-07-29-095854.png",
      "/projects/podcast-streaming-app/gallery/captura-de-pantalla-2026-07-29-095902.png",
      "/projects/podcast-streaming-app/gallery/captura-de-pantalla-2026-07-29-095910.png",
      "/projects/podcast-streaming-app/gallery/captura-de-pantalla-2026-07-29-095920.png"
    ],
    isFeatured: false
  },
  {
    id: "saas-bodegas-pos",
    slug: "saas-bodegas-pos",
    title: "SaaS Bodegas",
    category: { es: "PROYECTO EXPERIMENTAL", en: "EXPERIMENTAL PROJECT" },
    projectCategory: "experimental",
    status: "functional",
    subtitle: {
      es: "Prototipo experimental de punto de venta para explorar operaciones sin conexión, persistencia local y sincronización posterior.",
      en: "Experimental point-of-sale prototype exploring offline operations, local persistence, and later synchronization.",
    },
    tagline: {
      es: "Prototipo experimental de punto de venta para explorar operaciones sin conexión, persistencia local y sincronización posterior.",
      en: "Experimental point-of-sale prototype exploring offline operations, local persistence, and later synchronization.",
    },
    description: {
      es: "Prototipo experimental de punto de venta para explorar operaciones sin conexión, persistencia local y sincronización posterior.",
      en: "Experimental point-of-sale prototype exploring offline operations, local persistence, and later synchronization.",
    },
    techStack: ["TypeScript", "React", "Next.js", "Vite", "Tailwind CSS", "Lucide React", "Dexie.js", "IndexedDB", "NestJS", "Node.js", "Prisma ORM", "PostgreSQL", "Docker", "REST API"],
    contribution: {
      es: "Trabajé en el análisis de los flujos de venta, integración de componentes y validación funcional del prototipo.",
      en: "I worked on sales-flow analysis, component integration, and functional validation of the prototype.",
    },
    learnings: [
      { es: "Persistencia de información en el navegador.", en: "Browser-based data persistence." },
      { es: "Diseño de flujos de venta.", en: "Sales workflow design." },
      { es: "Exploración de sincronización después de trabajar sin conexión.", en: "Exploring synchronization after offline operation." },
    ],
    coverImage: "/projects/saas-bodegas-pos/cover.jpg",
    links: {
      video: "https://youtu.be/oDbNjL_c7dI",
    },
    screenshots: [
      "/projects/saas-bodegas-pos/gallery/captura-de-pantalla-2026-07-29-104359.png",
      "/projects/saas-bodegas-pos/gallery/captura-de-pantalla-2026-07-29-104406.png",
      "/projects/saas-bodegas-pos/gallery/captura-de-pantalla-2026-07-29-104421.png",
      "/projects/saas-bodegas-pos/gallery/captura-de-pantalla-2026-07-29-104430.png",
      "/projects/saas-bodegas-pos/gallery/captura-de-pantalla-2026-07-29-104438.png",
      "/projects/saas-bodegas-pos/gallery/captura-de-pantalla-2026-07-29-104443.png",
      "/projects/saas-bodegas-pos/gallery/captura-de-pantalla-2026-07-29-104454.png",
      "/projects/saas-bodegas-pos/gallery/captura-de-pantalla-2026-07-29-104507.png",
      "/projects/saas-bodegas-pos/gallery/captura-de-pantalla-2026-07-29-104512.png",
      "/projects/saas-bodegas-pos/gallery/captura-de-pantalla-2026-07-29-104534.png",
      "/projects/saas-bodegas-pos/gallery/captura-de-pantalla-2026-07-29-104546.png",
    ],
    isFeatured: false
  },
  {
    id: "tienda-catys",
    slug: "tienda-catys",
    title: "Tienda Catys",
    category: { es: "PROYECTO ACADÉMICO", en: "ACADEMIC PROJECT" },
    projectCategory: "academic",
    status: "functional",
    subtitle: {
      es: "Centraliza pedidos, productos, mesas, inventario y comandas dentro de un flujo de gestión gastronómica. Registra ventas, actualiza existencias y genera información para dashboards y reportes mediante React, APIs Java y SQL Server.",
      en: "Centralizes orders, products, tables, inventory, and kitchen tickets within a restaurant-management workflow. It records sales, updates stock, and generates dashboard and reporting information through React, Java APIs, and SQL Server.",
    },
    tagline: {
      es: "Centraliza pedidos, productos, mesas, inventario y comandas dentro de un flujo de gestión gastronómica. Registra ventas, actualiza existencias y genera información para dashboards y reportes mediante React, APIs Java y SQL Server.",
      en: "Centralizes orders, products, tables, inventory, and kitchen tickets within a restaurant-management workflow. It records sales, updates stock, and generates dashboard and reporting information through React, Java APIs, and SQL Server.",
    },
    description: {
      es: "Centraliza pedidos, productos, mesas, inventario y comandas dentro de un flujo de gestión gastronómica. Registra ventas, actualiza existencias y genera información para dashboards y reportes mediante React, APIs Java y SQL Server.",
      en: "Centralizes orders, products, tables, inventory, and kitchen tickets within a restaurant-management workflow. It records sales, updates stock, and generates dashboard and reporting information through React, Java APIs, and SQL Server.",
    },
    details: {
      es: "Tienda Catys organiza el flujo gastronómico desde la selección de productos hasta el registro de la venta y generación de comandas para cocina. La aplicación gestiona mesas, clientes, productos, insumos e inventario; al confirmar una venta, conserva el detalle y actualiza existencias. También incorpora vistas para pedidos de cocina, dashboard y reportes financieros. El backend combina Spring Boot, JPA, JDBC y SQL Server, mientras que React presenta las operaciones mediante formularios, paneles y consultas a APIs.",
      en: "Tienda Catys organizes restaurant workflows from product selection to sales registration and kitchen-ticket generation. The application manages tables, customers, products, supplies, and inventory; when a sale is confirmed, it stores transaction details and updates stock. It also includes kitchen-order, dashboard, and financial-report views. The backend combines Spring Boot, JPA, JDBC, and SQL Server, while React presents operations through forms, dashboards, and API queries.",
    },
    contribution: {
      es: "Diseñé y modelé los flujos de pedidos, ventas, mesas, productos e inventario. Integré React con APIs Java y persistencia relacional; además, validé ventas, actualización de stock, generación de comandas y pantallas de seguimiento.",
      en: "I designed and modeled workflows for orders, sales, tables, products, and inventory. I integrated React with Java APIs and relational persistence, then validated sales, stock updates, kitchen-ticket generation, and tracking views.",
    },
    learnings: [
      { es: "Modelado de ventas e inventario.", en: "Sales and inventory modeling." },
      { es: "Persistencia relacional con SQL Server.", en: "Relational persistence with SQL Server." },
      { es: "Integración entre React y APIs REST.", en: "Integration between React and REST APIs." },
      { es: "Consultas para dashboards y reportes.", en: "Queries for dashboards and reports." },
      { es: "Gestión de mesas, comandas y existencias.", en: "Management of tables, kitchen tickets, and stock." },
    ],
    techStack: ["Java", "Spring Boot", "Spring Data JPA", "JDBC", "SQL Server", "React", "Vite", "Tailwind CSS", "Docker Compose", "REST APIs"],
    coverImage: "/projects/tienda-catys/cover.jpg",
    links: {
      repository: "https://github.com/juanj983009-eng/Tienda-Catys-Java",
      video: "https://youtu.be/jEqSSWqL214",
    },
    screenshots: [
      "/projects/tienda-catys/gallery/captura-de-pantalla-2026-08-07-151919.png",
      "/projects/tienda-catys/gallery/captura-de-pantalla-2026-08-07-151957.png",
      "/projects/tienda-catys/gallery/captura-de-pantalla-2026-08-07-152003.png",
      "/projects/tienda-catys/gallery/captura-de-pantalla-2026-08-07-152010.png",
      "/projects/tienda-catys/gallery/captura-de-pantalla-2026-08-07-152019.png",
      "/projects/tienda-catys/gallery/captura-de-pantalla-2026-08-07-152026.png",
      "/projects/tienda-catys/gallery/captura-de-pantalla-2026-08-07-152050.png",
      "/projects/tienda-catys/gallery/captura-de-pantalla-2026-08-07-152101.png",
      "/projects/tienda-catys/gallery/captura-de-pantalla-2026-08-07-152109.png",
      "/projects/tienda-catys/gallery/captura-de-pantalla-2026-08-07-152116.png",
      "/projects/tienda-catys/gallery/captura-de-pantalla-2026-08-07-152122.png",
      "/projects/tienda-catys/gallery/captura-de-pantalla-2026-08-07-152128.png",
      "/projects/tienda-catys/gallery/captura-de-pantalla-2026-08-07-152135.png",
      "/projects/tienda-catys/gallery/captura-de-pantalla-2026-08-07-152141.png",
      "/projects/tienda-catys/gallery/captura-de-pantalla-2026-08-07-152150.png"
    ],
    isFeatured: true
  },
  {
    id: "biblioteca-digital",
    slug: "biblioteca-digital",
    title: "Biblioteca Digital",
    category: { es: "PROYECTO EXPERIMENTAL", en: "EXPERIMENTAL PROJECT" },
    projectCategory: "experimental",
    status: "functional",
    subtitle: {
      es: "Prototipo experimental de catálogo digital para explorar búsqueda, visualización y flujos simulados de préstamo o compra de libros.",
      en: "Experimental digital-catalog prototype exploring search, visualization, and simulated book borrowing or purchase workflows.",
    },
    tagline: {
      es: "Prototipo experimental de catálogo digital para explorar búsqueda, visualización y flujos simulados de préstamo o compra de libros.",
      en: "Experimental digital-catalog prototype exploring search, visualization, and simulated book borrowing or purchase workflows.",
    },
    description: {
      es: "Prototipo experimental de catálogo digital para explorar búsqueda, visualización y flujos simulados de préstamo o compra de libros.",
      en: "Experimental digital-catalog prototype exploring search, visualization, and simulated book borrowing or purchase workflows.",
    },
    techStack: [
      "Java 17",
      "Spring Boot 3.3",
      "Next.js 16 (App Router)",
      "React 19",
      "TypeScript",
      "PostgreSQL 16",
      "Redis 7",
      "Spring Data JPA / Hibernate",
      "Resilience4j",
      "TailwindCSS",
      "Three.js",
      "React Three Fiber",
      "Docker",
      "Docker Compose",
      "JUnit 5 / Testcontainers"
    ],
    contribution: {
      es: "Trabajé en la integración del catálogo, navegación, persistencia y pruebas funcionales del prototipo.",
      en: "I worked on catalog integration, navigation, persistence, and functional testing of the prototype.",
    },
    learnings: [
      { es: "Organización y consulta de catálogos.", en: "Catalog organization and querying." },
      { es: "Separación de responsabilidades.", en: "Separation of responsibilities." },
      { es: "Diseño de experiencias de búsqueda y selección.", en: "Designing search and selection experiences." },
    ],
    coverImage: "/projects/biblioteca-digital/cover.jpg",
    links: {
      repository: "https://github.com/juanj983009-eng/Libreria-Digital",
      video: "https://youtu.be/-wGJQhYD_iI",
    },
    screenshots: [
      "/projects/biblioteca-digital/gallery/captura-de-pantalla-2026-07-29-160125.png",
      "/projects/biblioteca-digital/gallery/captura-de-pantalla-2026-07-29-160131.png",
      "/projects/biblioteca-digital/gallery/captura-de-pantalla-2026-07-29-160142.png",
      "/projects/biblioteca-digital/gallery/captura-de-pantalla-2026-07-29-160150.png",
      "/projects/biblioteca-digital/gallery/captura-de-pantalla-2026-07-29-160159.png",
      "/projects/biblioteca-digital/gallery/captura-de-pantalla-2026-07-29-160212.png",
      "/projects/biblioteca-digital/gallery/captura-de-pantalla-2026-07-29-160225.png",
      "/projects/biblioteca-digital/gallery/captura-de-pantalla-2026-07-29-160236.png",
      "/projects/biblioteca-digital/gallery/captura-de-pantalla-2026-07-29-160241.png",
      "/projects/biblioteca-digital/gallery/captura-de-pantalla-2026-07-29-160251.png",
      "/projects/biblioteca-digital/gallery/captura-de-pantalla-2026-07-29-160256.png",
      "/projects/biblioteca-digital/gallery/captura-de-pantalla-2026-07-29-160302.png"
    ],
    isFeatured: false
  },
  {
    id: "clinicav2-stack",
    slug: "clinicav2-stack",
    title: "HealthTech 2026",
    category: { es: "PROYECTO ACADÉMICO", en: "ACADEMIC PROJECT" },
    projectCategory: "academic",
    status: "functional",
    subtitle: {
      es: "Prototipo académico de monitoreo clínico simulado para explorar la visualización y actualización de datos sintéticos en tiempo real.",
      en: "Academic simulated clinical-monitoring prototype exploring real-time visualization and updates of synthetic data.",
    },
    tagline: {
      es: "Prototipo académico de monitoreo clínico simulado para explorar la visualización y actualización de datos sintéticos en tiempo real.",
      en: "Academic simulated clinical-monitoring prototype exploring real-time visualization and updates of synthetic data.",
    },
    description: {
      es: "Prototipo académico de monitoreo clínico simulado para explorar la visualización y actualización de datos sintéticos en tiempo real.",
      en: "Academic simulated clinical-monitoring prototype exploring real-time visualization and updates of synthetic data.",
    },
    techStack: [
      "Java 17",
      "Spring Boot 3.x",
      "Spring Security (OAuth2/OIDC)",
      "Spring Data JPA",
      "React 19",
      "TypeScript",
      "PostgreSQL 15",
      "Redis 7",
      "Keycloak 24.0.5",
      "Nginx Proxy",
      "Docker",
      "Docker Compose",
      "Server-Sent Events (SSE)",
      "Tailwind CSS",
      "Lucide React"
    ],
    contribution: {
      es: "Trabajé en el análisis del flujo simulado, integración de componentes, visualización de datos y pruebas del prototipo.",
      en: "I worked on simulated-flow analysis, component integration, data visualization, and prototype testing.",
    },
    learnings: [
      { es: "Simulación y visualización de datos.", en: "Data simulation and visualization." },
      { es: "Actualizaciones de interfaz en tiempo real.", en: "Real-time interface updates." },
      { es: "Consideraciones al diseñar software para contextos sensibles.", en: "Considerations when designing software for sensitive contexts." },
    ],
    coverImage: "/projects/clinicav2-stack/cover.jpg",
    links: {
      repository: "https://github.com/juanj983009-eng/Clinica_V2",
      video: "https://youtu.be/xR0LZ8JPsU0",
    },
    screenshots: [
      "/projects/clinicav2-stack/gallery/captura-de-pantalla-2026-07-29-161811.png",
      "/projects/clinicav2-stack/gallery/captura-de-pantalla-2026-07-29-161816.png",
      "/projects/clinicav2-stack/gallery/captura-de-pantalla-2026-07-29-161822.png",
      "/projects/clinicav2-stack/gallery/captura-de-pantalla-2026-07-29-161828.png",
      "/projects/clinicav2-stack/gallery/captura-de-pantalla-2026-07-29-161833.png",
      "/projects/clinicav2-stack/gallery/captura-de-pantalla-2026-07-29-161840.png",
      "/projects/clinicav2-stack/gallery/captura-de-pantalla-2026-07-29-161844.png",
      "/projects/clinicav2-stack/gallery/captura-de-pantalla-2026-07-29-161851.png",
      "/projects/clinicav2-stack/gallery/captura-de-pantalla-2026-07-29-161858.png",
      "/projects/clinicav2-stack/gallery/captura-de-pantalla-2026-07-29-161903.png",
      "/projects/clinicav2-stack/gallery/captura-de-pantalla-2026-07-29-161913.png",
      "/projects/clinicav2-stack/gallery/captura-de-pantalla-2026-07-29-161918.png",
      "/projects/clinicav2-stack/gallery/captura-de-pantalla-2026-07-29-161927.png"
    ],
    isFeatured: false
  },
  {
    id: "olimpiadas-peru",
    slug: "olimpiadas-peru",
    title: "Olimpiadas Perú 2026",
    category: { es: "PROYECTO ACADÉMICO", en: "ACADEMIC PROJECT" },
    projectCategory: "academic",
    status: "functional",
    subtitle: {
      es: "Prototipo académico de gestión deportiva para practicar flujos simulados de acreditación, programación y registro de resultados.",
      en: "Academic sports-management prototype for practicing simulated accreditation, scheduling, and result-recording workflows.",
    },
    tagline: {
      es: "Prototipo académico de gestión deportiva para practicar flujos simulados de acreditación, programación y registro de resultados.",
      en: "Academic sports-management prototype for practicing simulated accreditation, scheduling, and result-recording workflows.",
    },
    description: {
      es: "Prototipo académico de gestión deportiva para practicar flujos simulados de acreditación, programación y registro de resultados.",
      en: "Academic sports-management prototype for practicing simulated accreditation, scheduling, and result-recording workflows.",
    },
    techStack: [
      "Java 17",
      "Jakarta Servlets",
      "Apache Tomcat 10",
      "PostgreSQL 15",
      "Docker & Docker Compose",
      "HikariCP",
      "JavaScript (ES6+)",
      "HTML5",
      "CSS3 / Design Tokens",
      "Bootstrap 5",
      "Maven"
    ],
    contribution: {
      es: "Trabajé en el modelado de los flujos administrativos, integración de la aplicación, pruebas y correcciones.",
      en: "I worked on administrative workflow modeling, application integration, testing, and corrections.",
    },
    learnings: [
      { es: "Modelado de procesos administrativos.", en: "Administrative process modeling." },
      { es: "Validación de formularios.", en: "Form validation." },
      { es: "Persistencia relacional y seguimiento de resultados.", en: "Relational persistence and result tracking." },
    ],
    coverImage: "/projects/olimpiadas-peru/cover.jpg",
    links: {
      repository: "https://github.com/juanj983009-eng/Olimpiadas-Peru",
      video: "https://youtu.be/KbHmRWK1-ws",
    },
    screenshots: [
      "/projects/olimpiadas-peru/gallery/captura-de-pantalla-2026-07-29-163441.png",
      "/projects/olimpiadas-peru/gallery/captura-de-pantalla-2026-07-29-163449.png",
      "/projects/olimpiadas-peru/gallery/captura-de-pantalla-2026-07-29-163455.png",
      "/projects/olimpiadas-peru/gallery/captura-de-pantalla-2026-07-29-163502.png",
      "/projects/olimpiadas-peru/gallery/captura-de-pantalla-2026-07-29-163509.png",
      "/projects/olimpiadas-peru/gallery/captura-de-pantalla-2026-07-29-163516.png",
      "/projects/olimpiadas-peru/gallery/captura-de-pantalla-2026-07-29-163523.png",
      "/projects/olimpiadas-peru/gallery/captura-de-pantalla-2026-07-29-163531.png",
      "/projects/olimpiadas-peru/gallery/captura-de-pantalla-2026-07-29-163541.png",
      "/projects/olimpiadas-peru/gallery/captura-de-pantalla-2026-07-29-163550.png",
      "/projects/olimpiadas-peru/gallery/captura-de-pantalla-2026-07-29-163602.png"
    ],
    isFeatured: false
  }
];

export default PROJECTS;
